### ISSUE TITLE
Fixed-length buffers

### ISSUE THREAD

**Issue by TheLoneWolfling** [incrediblesound/huo#11]
A program consisting of >= 256 zeros crashes. I haven't checked yet, but I suspect that many other tokens of length >= 256 will also crash.

Simple reproduction:

```
python -c 'print("0"*1000)' >crash.txt
huo crash.txt
```

Considering you're using longs internally _anyways_, it may be simplest to just throw an error if you get too many characters in a single token.

**Comment by TheLoneWolfling** [comment]
Yep, other tokens are affected. A thousand 'a's, or a string consisting of 1000 characters, will both crash it, for instance.

**Comment by TheLoneWolfling** [comment]
Also issue #9 comes into play here.

**Comment by TheLoneWolfling** [comment]
If I wrote up a patch to replace your fixed-length buffers with heap-allocated ones, would you accept it?

**Comment by incrediblesound** [comment]
Yes, in general I am pretty open about pull requests. If you do something to improve the code I'll definitely accept the pull request.
