### ISSUE TITLE
Array set index out of bounds

### ISSUE THREAD

**Issue by TheLoneWolfling** [incrediblesound/huo#26]
If I set an element past the end of an array, should it
1. Error out
2. Silently do nothing
3. Silently append the value to the array
4. Set all elements between the previous end of the array and the element set to undef.

(Personally? 1 or 4)

**Comment by incrediblesound** [comment]
I think I like option 4 in this case.

**Comment by TheLoneWolfling** [comment]
Easy enough to do.
