### ISSUE TITLE
Return example regression

### ISSUE THREAD

**Issue by TheLoneWolfling** [incrediblesound/huo#30]
For reference:

```
(def pair x y (return [x, y]))
(def nest x y (return [x, [1, y]]))
(let z (pair 10 1))
(let y (nest "hey" "you"))
(print x)
(print y)
```

Previously:

```
[ 10, 1 ]
[ "hey", [ 1, "you" ] ]
```

Now:

```
[ "x", "y" ]
[ "x", [ 1, "y" ] ]
```

**Comment by TheLoneWolfling** [comment]
Found the problem:

This is a problem with doing things lazily - in this case, binding late. What's happening is that nothing ever actually goes over the array to substitute variables for their values. I.e. [here](https://github.com/incrediblesound/huo/blob/master/execute.c#L130).

**Comment by incrediblesound** [comment]
I see, so the let_bind functions store x and y as references to the function parameters inside the scope of the function, but when that value is returned the scope is lost and those variables loose meaning. That's slightly painful, but I think what needs to be done is to replace those variables with the values before exiting the function scope, and thankfully we have acess to both the value and the scope around line 136 in execute.c.
