### ISSUE TITLE
Freeing execution bundle before pthread join

### ISSUE THREAD

**Issue by tomsmeding** [incrediblesound/huo#4]
Forgive me for not actually testing this, but shouldn't [these two lines](https://github.com/incrediblesound/huo/blob/master/execution_functions/parallel_execution.c#L25-26) be swapped?
It appears to me that the thread might still be using the data at the point when you already free it.

Awesome work otherwise!

**Comment by incrediblesound** [comment]
Thank you for pointing this out! I think it definitely makes more sense to free the execution bundle after pthread join.
