### ISSUE TITLE
Operations on arrays

### ISSUE THREAD

**Issue by TheLoneWolfling** [incrediblesound/huo#44]
Currently only add is supported on arrays.

Would it make sense to have all built-ins that aren't otherwise supported automatically map themselves over an array?

It seems kind of odd that you can element-wise add two arrays, but not subtract them (for instance).

**Comment by incrediblesound** [comment]
Yeah that was part of the plan. I started matrix multiplication but that was tricky and then I got sidetracked. If you'd like to add any of those feel free, otherwise I'll add them eventually.

**Comment by TheLoneWolfling** [comment]
Ok. I shall do that then.

**Comment by TheLoneWolfling** [comment]
Do you want a dedicated matrix multiplication keyword? If so, what?

**Comment by incrediblesound** [comment]
Yeah I think ultimately we should have a special keyword for matrix multiply although I'm not sure exactly what it should be. We might even be able to just add it to the core library instead of implementing it natively.
