### ISSUE TITLE
Make array doesn't check for EOF

### ISSUE THREAD

**Issue by TheLoneWolfling** [incrediblesound/huo#7]
The following program:

```
[
```

(that is, a single opening bracket)

crashes with a segfault.

Looking at build_array.c, it's pretty obvious why. You need to ensure that counter doesn't run off the end of the file if you want it to be robust against input errors. I'm not sure if you care about that.

**Comment by TheLoneWolfling** [comment]
Actually, so does unbalanced strings:

```
"
```

**Comment by incrediblesound** [comment]
Thank you! At first I was only concerned with implementing features, but I'm starting to tackle these things now that I've successfully implemented many of the core features. This kind of issue is very helpful for me to keep track of things I need to implement.

**Comment by TheLoneWolfling** [comment]
Same with `if`, by the way.

I shall continue until I get bored or you tell me to stop, then :)

**Comment by TheLoneWolfling** [comment]
'"', '[', 'read', 'let', 'def', 'for', 'map', 'set', and 'if' all have this problem so far.

**Comment by TheLoneWolfling** [comment]
Testing, and these all seem to work now. Closing.
