### ISSUE TITLE
Incorrect reference by import

### ISSUE THREAD

**Issue by TheLoneWolfling** [incrediblesound/huo#8]
[This](https://github.com/incrediblesound/huo/blob/master/store_defs.c#L20):

```
struct Tree * imported_ast = read_import(ast->children[i]->children[0]->content.data.str);
```

Should be this:

```
struct Tree * imported_ast = read_import(ast->children[i]->children[0]->children[0]->content.data.str);
```

As-is, you're reading uninitialized memory.

(Sidenote: original issue exists elsewhere, but I'll pull it up if/when I stumble across it.)

**Comment by incrediblesound** [comment]
Good catch, I'll double check on that one. It's a little unclear when I start referencing children of children anyway, I think it might be better to store a reference in a well named variable before passing into read_import to make it clearer what is happening there.

**Comment by TheLoneWolfling** [comment]
I agree. This is just a "quick fix".

**Comment by incrediblesound** [comment]
I investigated this and it looks like the read_import function is pointing to the right value but that the tokens struct didn't like being allocated on the stack. I changed it to a heap allocation and now the "imports" example works.
